apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: backend
          image: 580534058667.dkr.ecr.us-east-2.amazonaws.com/listenup-api:latest
          ports:
            - containerPort: 8889
          env:
            - name: REDIS_URL
              value: redis://redis:6379