services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: listenup-client
    ports:
      - "5173:80"  
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: listenup-api
    ports:
      - "8889:8889"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"