services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: listenup-client
    ports:
      - "5173:80"  
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: listenup-api