services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: playlifts-api
    ports:
      - "8889:8889"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
