version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: playlifts-api
    ports:
      - "8889:8889"
    depends_on:
      - redis
    env_file:
      - backend/.env
    environment:
      - REDIS_URL=${REDIS_URL}

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    depends_on:
      - redis
    env_file:
      - backend/.env
    environment:
      - REDIS_URL=${REDIS_URL}

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
